---
# Dependabot configuration for automatic dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Python dependencies (pip-tools)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only look for version updates in .in files
    versioning-strategy: "increase-if-necessary"
    # Group updates by dependency type
    groups:
      python-packages:
        patterns: ["*"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns: ["*"]

  # Node.js dependencies (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns: ["*"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns: ["*"]
