default_language_version:
    python: python3.13
repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: v7.5.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements-development.in
        files: requirements-(base|development).in
        args: [ "--strip-extras", "--no-header", requirements/source/requirements-development.in, "--output-file", requirements/generated/requirements-development.txt, "--no-annotate"]
      - id: pip-compile
        name: pip-compile requirements-production.in
        files: requirements-(base|production).in
        args: [ "--strip-extras", "--no-header", requirements/source/requirements-production.in, "--output-file", requirements/generated/requirements-production.txt, "--no-annotate"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
