from app.utils import register_form_view

from .forms import (
    ApplyHeadOfficeHoldPaymentsForm,
    ApplyHeadOfficeInterventionForm,
    BankAccountForm,
    BankAccountSearchForm,
    ChangeOfficeActiveStatusForm,
    ChangeOfficeContactDetailsForm,
    ChangeOfficeContractManagerForm,
    ChangeOfficeDebtRecoveryForm,
    ChangeOfficeFalseBalanceForm,
    ChangeOfficeHoldPaymentsFlagForm,
    ChangeOfficeIntervenedForm,
    PaymentMethodForm,
    RemoveHeadOfficeHoldPaymentsForm,
    RemoveHeadOfficeInterventionForm,
    UpdateVATRegistrationNumberForm,
)
from .views import (
    AddBankAccountFormView,
    ApplyHeadOfficeHoldPaymentsFormView,
    ApplyHeadOfficeInterventionFormView,
    ChangeContractManagerFormView,
    ChangeOfficeContactDetailsFormView,
    ChangeOfficeDebtRecoveryFormView,
    ChangeOfficeFalseBalanceFormView,
    ChangeOfficeHoldPaymentsFlagFormView,
    ChangeOfficeIntervenedFormView,
    OfficeActiveStatusFormView,
    PaymentMethodFormView,
    RemoveHeadOfficeHoldPaymentsFormView,
    RemoveHeadOfficeInterventionFormView,
    SearchBankAccountFormView,
    UpdateVATRegistrationNumberFormView,
)


def register_views(bp):
    register_form_view(
        form_class=UpdateVATRegistrationNumberForm,
        view_class=UpdateVATRegistrationNumberFormView,
        blueprint=bp,
        endpoint="add_office_vat_number",
    )
    register_form_view(
        form_class=PaymentMethodForm,
        view_class=PaymentMethodFormView,
        blueprint=bp,
        endpoint="payment_method_form",
    )
    register_form_view(
        form_class=ChangeOfficeActiveStatusForm,
        view_class=OfficeActiveStatusFormView,
        blueprint=bp,
        endpoint="office_active_status_form",
    )
    register_form_view(
        form_class=BankAccountSearchForm,
        view_class=SearchBankAccountFormView,
        blueprint=bp,
        endpoint="search_bank_account",
    )
    register_form_view(
        form_class=ChangeOfficeContactDetailsForm,
        view_class=ChangeOfficeContactDetailsFormView,
        blueprint=bp,
        endpoint="change_office_contact_details_form",
    )
    register_form_view(
        form_class=BankAccountForm,
        view_class=AddBankAccountFormView,
        blueprint=bp,
        endpoint="add_office_bank_account",
    )
    register_form_view(
        form_class=ChangeOfficeContractManagerForm,
        view_class=ChangeContractManagerFormView,
        blueprint=bp,
        endpoint="change_office_contract_manager",
    )
    register_form_view(
        form_class=ChangeOfficeFalseBalanceForm,
        view_class=ChangeOfficeFalseBalanceFormView,
        blueprint=bp,
        endpoint="change_office_false_balance",
    )
    register_form_view(
        form_class=ChangeOfficeIntervenedForm,
        view_class=ChangeOfficeIntervenedFormView,
        blueprint=bp,
        endpoint="change_office_intervened",
    )
    register_form_view(
        form_class=ApplyHeadOfficeInterventionForm,
        view_class=ApplyHeadOfficeInterventionFormView,
        blueprint=bp,
        endpoint="apply_head_office_intervention",
    )
    register_form_view(
        form_class=RemoveHeadOfficeInterventionForm,
        view_class=RemoveHeadOfficeInterventionFormView,
        blueprint=bp,
        endpoint="remove_head_office_intervention",
    )
    register_form_view(
        form_class=ChangeOfficeDebtRecoveryForm,
        view_class=ChangeOfficeDebtRecoveryFormView,
        blueprint=bp,
        endpoint="change_office_debt_recovery",
    )
    register_form_view(
        form_class=ChangeOfficeHoldPaymentsFlagForm,
        view_class=ChangeOfficeHoldPaymentsFlagFormView,
        blueprint=bp,
        endpoint="change_office_hold_payments_flag",
    )
    register_form_view(
        form_class=ApplyHeadOfficeHoldPaymentsForm,
        view_class=ApplyHeadOfficeHoldPaymentsFormView,
        blueprint=bp,
        endpoint="apply_head_office_hold_payments_flag",
    )
    register_form_view(
        form_class=RemoveHeadOfficeHoldPaymentsForm,
        view_class=RemoveHeadOfficeHoldPaymentsFormView,
        blueprint=bp,
        endpoint="remove_head_office_hold_payments_flag",
    )
