# Default values for laa-manage-a-providers-data.
# These can be overwritten by values defined in environment specific values files.
replicaCount: 1

image:
  repository: laa-manage-a-providers-data
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  containerPort: 8000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "modsec"
  cluster:
    name: green
    weight: '100'
  tls: {}

whitelist:
  enabled: true

resources: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}

envVars:
  SECRET_KEY:
    secret:
      name: secret-key
      key: value
      optional: false
  SENTRY_DSN:
    secret:
      name: sentry
      key: dsn
  SENTRY_TRACES_SAMPLE_RATE:
    configmap:
      name: sentry-config
      key: traces_sample_rate
      optional: true
  SENTRY_PROFILES_SAMPLE_RATE:
    configmap:
      name: sentry-config
      key: profiles_sample_rate
      optional: true
  CLIENT_ID:
    secret:
      name: entra-id
      key: client_id
  CLIENT_SECRET:
    secret:
      name: entra-id
      key: client_secret
  CLIENT_SECRET_THUMBPRINT:
    secret:
      name: entra-id
      key: client_secret_thumbprint
  AUTHORITY:
    secret:
      name: entra-id
      key: authority
  REDIRECT_URI:
    secret:
      name: entra-id
      key: redirect_uri
