# Default values for laa-manage-a-providers-data.
# These can be overwritten by values defined in environment specific values files.
replicaCount: 1

image:
  repository: laa-manage-a-providers-data
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  containerPort: 8000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "modsec"
  cluster:
    name: green
    weight: '100'
  tls: {}

whitelist:
  enabled: true

resources: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}

envVars:
  SECRET_KEY:
    secret:
      name: secret-key
      key: value
      optional: false
  PDA_URL:
    configmap:
      name: provider-data-api
      key: url
  PDA_ENVIRONMENT:
    configmap:
      name: provider-data-api
      key: environment
  PDA_API_KEY:
    secret:
      name: provider-data-api
      key: api_key
  PASSWORD:
    secret:
      name: password
      key: value
