{{- if .Values.ingress.enabled }}
{{- $fullName := include "laa-manage-a-providers-data.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "laa-manage-a-providers-data.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "413,502,504"
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- if .Values.whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "laa-manage-a-providers-data.whitelist" . }}"
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-get-access"
      SecRuleUpdateTargetById 920273 "!ARGS:search"
      SecRuleUpdateTargetById 920273 "!ARGS_NAMES:search"
      SecRuleUpdateTargetById 920273 "!REQUEST_URI"

      SecRuleUpdateTargetById 920240 "!ARGS:search"
      SecRuleUpdateTargetById 920240 "!ARGS_NAMES:search"
      SecRuleUpdateTargetById 920240 "!REQUEST_URI"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
       - "{{ .Values.ingress.host }}"
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}