name: Feature Branch

run-name: Feature - ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - reopened

jobs:
  test:
     name: Test
     uses: ./.github/workflows/test.yml

  static-analysis:
    name: Static Analysis
    needs: test
    uses: ./.github/workflows/static-analysis.yml

  build-and-push:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-ephemeral:
     name: Ephemeral
     uses: ./.github/workflows/deploy-ephemeral.yml
     needs: build-and-push
     with:
       environment: uat
       ECR_REGION: ${{vars.ECR_REGION}}
       ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
     secrets:
       ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
       ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
       KUBE_CERT: ${{ secrets.KUBE_CERT }}
       KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
       KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
       KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-uat:
     name: UAT
     uses: ./.github/workflows/deploy.yml
     needs: build-and-push
     with:
       environment: uat
       ECR_REGION: ${{vars.ECR_REGION}}
       ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
       DEPLOYMENT_URL: "https://laa-manage-a-providers-data-uat.cloud-platform.service.justice.gov.uk"
     secrets:
       ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
       ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
       KUBE_CERT: ${{ secrets.KUBE_CERT }}
       KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
       KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
       KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
